# -*- coding: utf-8 -*-
"""kadai_014.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/100gA-uNn9fraUyRabr7RUkMEMri-o9ow
"""

price1 = 100
price2 = 200
tax = 1.1
def total():
    total_p= price1 + price2
    print (total_p*tax)

total()