# -*- coding: utf-8 -*-
"""kadai_005.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sn-YEyuLYjYKekZwlfVDQrjpg1quWVxy
"""

top_side = 10
bottom_side = 20
height = 5

print(str((top_side + bottom_side) * height / 2 )+ "㎠")