# -*- coding: utf-8 -*-
"""kadai_011.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GGqrw8KMF8dKUYCIbDXOsvqDNgo9wg2I
"""

for i in ("水","金","地","火","木","土","天","海","冥"):
 print(i)

list = ("水","金","地","火","木","土","天","海","冥")

i = 0

while i <= 8:
  print(list[i])
  i  = i + 1