# -*- coding: utf-8 -*-
"""kadai_015.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ncFk50qSgRKO8N2I5zRUPJSq4Crp6dOl
"""

# クラスの定義
class Human:
    #コンストラクタの定義
    def __init__(self,name,age):
        self.name = name
        self.age = age
#メソッドを定義
    def set_name(self,name):
      self.name = name
    def set_age(self,age):
      self_name = age
#printinfoのメソッドを定義
    def printinfo(self):
      print(self.name)
      print(self.age)

#インスタンス化
human = Human("侍太郎",30)
#メソッドにアクセスして実行
human.printinfo()