# -*- coding: utf-8 -*-
"""kadai_017.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zSWmTBtTVKTXC7gd3gPhCqdD2iyeQV5R
"""

#クラスの定義
class Human:
  #属性の定義
  def __init__(self,name,age):
     self.name = name
     self.age = age

  def check_adult(self):

   #if文
     if self.age >= 20:
         print("{}は大人です".format(self.name))

     else:
         print("{}は大人ではありません".format(self.name))

 #インスタンスの作成
user = [ ["侍四郎",25],["侍花子",15]]

#listにインスタンスのリストを入れる
human_list = []
for d in user:
  human_list.append((d[0],d[1]))

#listよりインスタンスのメソッドを実行
i = 0
for h in human_list:
   Human(h[0],h[1]).check_adult()